# *Lung Cancer Prediction*



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Preprocessing Data**

In [2]:
df=pd.read_csv("/content/sample_data/lung cancer.csv")

In [3]:
df.head(5)

GENDER   AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M  69.0      1.0             2.0      2.0            1.0   
1      M  74.0      2.0             1.0      1.0            1.0   
2      F  59.0      1.0             1.0      1.0            2.0   
3      M  63.0      2.0             2.0      2.0            1.0   
4      F  63.0      1.0             2.0      1.0            1.0   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0              1.0       2.0       1.0       2.0                2.0       2.0   
1              2.0       2.0       2.0       1.0                1.0       1.0   
2              1.0       2.0       1.0       2.0                1.0       2.0   
3              1.0       1.0       1.0       1.0                2.0       1.0   
4              1.0       1.0       NaN       2.0                1.0       2.0   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                  2.0                    2.0         2.0         YES  
1                  2.0                    2.0         2.0         YES  
2                  2.0                    1.0         2.0          NO  
3                  1.0                    2.0         2.0          NO  
4                  2.0                    1.0         1.0          NO

In [4]:
df.tail(5)

GENDER   AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
304      F   NaN      1.0             1.0      1.0            2.0   
305      M  70.0      2.0             1.0      1.0            1.0   
306      M  58.0      2.0             1.0      1.0            1.0   
307      M  67.0      2.0             1.0      2.0            NaN   
308      M  62.0      1.0             1.0      1.0            2.0   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
304              2.0       NaN       1.0       NaN                2.0   
305              1.0       2.0       2.0       2.0                2.0   
306              1.0       1.0       2.0       2.0                2.0   
307              1.0       2.0       2.0       1.0                2.0   
308              NaN       2.0       2.0       2.0                NaN   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
304       2.0                  2.0                    2.0         1.0   
305       2.0                  2.0                    NaN         2.0   
306       NaN                  1.0                    1.0         2.0   
307       2.0                  2.0                    1.0         2.0   
308       1.0                  1.0                    2.0         1.0   

    LUNG_CANCER  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES

In [5]:
df.shape

(309, 16)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   GENDER                 309 non-null    object 
 1   AGE                    302 non-null    float64
 2   SMOKING                306 non-null    float64
 3   YELLOW_FINGERS         307 non-null    float64
 4   ANXIETY                306 non-null    float64
 5   PEER_PRESSURE          305 non-null    float64
 6   CHRONIC DISEASE        306 non-null    float64
 7   FATIGUE                305 non-null    float64
 8   ALLERGY                300 non-null    float64
 9   WHEEZING               305 non-null    float64
 10  ALCOHOL CONSUMING      301 non-null    float64
 11  COUGHING               303 non-null    float64
 12  SHORTNESS OF BREATH    304 non-null    float64
 13  SWALLOWING DIFFICULTY  303 non-null    float64
 14  CHEST PAIN             308 non-null    float64
 15  LUNG_C

In [7]:
df.describe().T

count       mean       std   min   25%   50%   75%  \
AGE                    302.0  62.850993  7.785815  38.0  58.0  62.0  69.0   
SMOKING                306.0   1.562092  0.496942   1.0   1.0   2.0   2.0   
YELLOW_FINGERS         307.0   1.566775  0.496330   1.0   1.0   2.0   2.0   
ANXIETY                306.0   1.496732  0.500808   1.0   1.0   1.0   2.0   
PEER_PRESSURE          305.0   1.504918  0.500797   1.0   1.0   2.0   2.0   
CHRONIC DISEASE        306.0   1.506536  0.500776   1.0   1.0   2.0   2.0   
FATIGUE                305.0   1.675410  0.468991   1.0   1.0   2.0   2.0   
ALLERGY                300.0   1.556667  0.497609   1.0   1.0   2.0   2.0   
WHEEZING               305.0   1.560656  0.497123   1.0   1.0   2.0   2.0   
ALCOHOL CONSUMING      301.0   1.554817  0.497814   1.0   1.0   2.0   2.0   
COUGHING               303.0   1.577558  0.494765   1.0   1.0   2.0   2.0   
SHORTNESS OF BREATH    304.0   1.641447  0.480366   1.0   1.0   2.0   2.0   
SWALLOWING DIFFICULTY  303.0   1.468647  0.499842   1.0   1.0   1.0   2.0   
CHEST PAIN             308.0   1.555195  0.497753   1.0   1.0   2.0   2.0   

                        max  
AGE                    87.0  
SMOKING                 2.0  
YELLOW_FINGERS          2.0  
ANXIETY                 2.0  
PEER_PRESSURE           2.0  
CHRONIC DISEASE         2.0  
FATIGUE                 2.0  
ALLERGY                 2.0  
WHEEZING                2.0  
ALCOHOL CONSUMING       2.0  
COUGHING                2.0  
SHORTNESS OF BREATH     2.0  
SWALLOWING DIFFICULTY   2.0  
CHEST PAIN              2.0

In [8]:
df=df.drop_duplicates()

In [9]:
df.isnull().sum()

GENDER                   0
AGE                      7
SMOKING                  3
YELLOW_FINGERS           2
ANXIETY                  3
PEER_PRESSURE            4
CHRONIC DISEASE          3
FATIGUE                  4
ALLERGY                  9
WHEEZING                 4
ALCOHOL CONSUMING        8
COUGHING                 6
SHORTNESS OF BREATH      5
SWALLOWING DIFFICULTY    6
CHEST PAIN               1
LUNG_CANCER              0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
l=LabelEncoder()

In [12]:
df['GENDER']=l.fit_transform(df['GENDER'])
df['LUNG_CANCER']=l.fit_transform(df['LUNG_CANCER'])

In [13]:
X = df.drop(columns=['LUNG_CANCER']).values
y = df['LUNG_CANCER'].values

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
m=SimpleImputer(missing_values=np.nan,strategy="mean")
z=m.fit(X)
X=z.transform(X)

In [16]:
df.head(5)

GENDER   AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1  69.0      1.0             2.0      2.0            1.0   
1       1  74.0      2.0             1.0      1.0            1.0   
2       0  59.0      1.0             1.0      1.0            2.0   
3       1  63.0      2.0             2.0      2.0            1.0   
4       0  63.0      1.0             2.0      1.0            1.0   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0              1.0       2.0       1.0       2.0                2.0       2.0   
1              2.0       2.0       2.0       1.0                1.0       1.0   
2              1.0       2.0       1.0       2.0                1.0       2.0   
3              1.0       1.0       1.0       1.0                2.0       1.0   
4              1.0       1.0       NaN       2.0                1.0       2.0   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                  2.0                    2.0         2.0            1  
1                  2.0                    2.0         2.0            1  
2                  2.0                    1.0         2.0            0  
3                  1.0                    2.0         2.0            0  
4                  2.0                    1.0         1.0            0

**Feature Selection**

In [17]:
from sklearn.feature_selection import SelectPercentile

In [18]:
from sklearn.feature_selection import chi2,f_classif

In [19]:
FS=SelectPercentile(score_func= chi2, percentile=80)
X=FS.fit_transform(X,y)

In [20]:
FS.get_support()

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [21]:
X.shape

(297, 12)

In [22]:
selected_feature_indices = FS.get_support(indices=True)
selected_feature_names = df.columns[selected_feature_indices]
print(selected_feature_names)


Index(['AGE', 'YELLOW_FINGERS', 'ANXIETY', 'PEER_PRESSURE', 'CHRONIC DISEASE',
       'FATIGUE ', 'ALLERGY ', 'WHEEZING', 'ALCOHOL CONSUMING', 'COUGHING',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN'],
      dtype='object')


**Split Data**

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

 Data Scaling

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [27]:
X

array([[ 0.77430871,  0.89062918,  1.02581476, ...,  0.85231465,
         1.0859933 ,  0.89253662],
       [ 1.42142551, -1.13041396, -0.98478217, ..., -1.19746687,
         1.0859933 ,  0.89253662],
       [-0.51992487, -1.13041396, -0.98478217, ...,  0.85231465,
        -0.93980189,  0.89253662],
       ...,
       [-0.64934823, -1.13041396, -0.98478217, ...,  0.        ,
        -0.93980189,  0.89253662],
       [ 0.515462  , -1.13041396,  1.02581476, ...,  0.85231465,
        -0.93980189,  0.89253662],
       [-0.1316548 , -1.13041396, -0.98478217, ..., -1.19746687,
         1.0859933 , -1.12418735]])

## Algorithms

**Support Vector Classifiction**

In [28]:
from sklearn.svm import SVC

In [29]:
SV = SVC(kernel="rbf", gamma=0.5, C=1.0)
SV.fit(X_train,y_train)

SVC(gamma=0.5)

In [30]:
pred_sv=SV.predict(X_test)

**Evalute SVC Algorithm**

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn import metrics

Calculate accuracy, precision, recall, and F1-score

In [32]:
accuracy = accuracy_score(y_test, pred_sv)
precision = precision_score(y_test, pred_sv)
recall = recall_score(y_test, pred_sv)
f1 = f1_score(y_test, pred_sv)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.9166666666666666
Precision: 0.9322033898305084
Recall: 0.9821428571428571
F1 Score: 0.9565217391304348


In [33]:
metrics.accuracy_score(y_test, pred_sv)

0.9166666666666666

**Decision Tree Algorithm**

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
DT= DecisionTreeClassifier(criterion='entropy', max_depth=5)
DT.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [36]:
pred_dt=DT.predict(X_test)

**Evalute Decision Tree Algorithm**

In [37]:
precision = precision_score(y_test, pred_dt)
recall = recall_score(y_test, pred_dt)
f1 = f1_score(y_test, pred_dt)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9166666666666666
Precision: 0.9807692307692307
Recall: 0.9107142857142857
F1 Score: 0.9444444444444444


In [38]:
metrics.accuracy_score(y_test,pred_dt)

0.9

**KNN Algorithm**

In [39]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=20)
kn.fit(X_train,y_train)


KNeighborsClassifier(n_neighbors=20)

In [40]:
pred_knn=kn.predict(X_test)

**Evalute KNN Algorithm**

In [41]:
precision = precision_score(y_test, pred_knn)
recall = recall_score(y_test, pred_knn)
f1 = f1_score(y_test, pred_knn)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9166666666666666
Precision: 0.9333333333333333
Recall: 1.0
F1 Score: 0.9655172413793104


In [42]:
metrics.accuracy_score(y_test, pred_knn)


0.9333333333333333

**Random Forest Algorithm**

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
RS=RandomForestClassifier(n_estimators=15)

In [45]:
RS.fit(X_train,y_train)

RandomForestClassifier(n_estimators=15)

In [46]:
pred_rs=RS.predict(X_test)

Evalute Random forest Algorithm

In [47]:
precision = precision_score(y_test, pred_rs)
recall = recall_score(y_test, pred_rs)
f1 = f1_score(y_test, pred_rs)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.9166666666666666
Precision: 0.9642857142857143
Recall: 0.9642857142857143
F1 Score: 0.9642857142857143


In [48]:
metrics.accuracy_score(y_test,pred_rs)

0.9333333333333333

In [49]:
cm=confusion_matrix(y_test,pred_rs)

In [50]:
cm

array([[ 2,  2],
       [ 2, 54]])